<a href="https://colab.research.google.com/github/HemavathiRamamoorthy/Python/blob/main/NumpyAssignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1. Create a 5X2 integer array from a range between 100 to 200 such that the difference between each element is 10 


In [ ]:
import numpy as np

print("Creating 5X2 array using numpy.arange")
sampleArray = np.arange(100, 200, 10)
sampleArray = sampleArray.reshape(5,2)
print (sampleArray)

Creating 5X2 array using numpy.arange
[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


# 2. Write a NumPy program to create a 3x3x3 array filled with arbitrary values and find the minimum and maximum values

In [ ]:
x = np.random.random((3, 3, 3))
print(x)
xMin, xMax = x.min(), x.max()
print("\nMin value",xMin)
print("Max Value",xMax)

[[[0.56169311 0.84393267 0.85281291]
  [0.00428961 0.81444992 0.80100257]
  [0.39589254 0.50411058 0.33928334]]

 [[0.95471907 0.77644557 0.30818168]
  [0.54962591 0.50286232 0.36742334]
  [0.77268101 0.41039678 0.44828735]]

 [[0.17199733 0.24380025 0.13803161]
  [0.05272969 0.53220098 0.88529141]
  [0.53634986 0.36075663 0.90604223]]]

Min value 0.004289608886572149
Max Value 0.9547190688614401


# 3. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5. 


In [ ]:
x = np.diag([1, 2, 3, 4, 5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


# 4. Given an array 
 arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
  i) 
Extract all odd numbers from arr 
 ii) Replace all odd numbers in arr with -1 

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
#i) Extract all odd number
print(arr[arr % 2 == 1])
#replace odd number with -1
arr[arr % 2 == 1]=-1
print(arr)

[1 3 5 7 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


#5.Write a NumPy program to create a 3x3 identity matrix, i.e. diagonal elements are 1,the rest are 0. 


In [ ]:
identityMatrix = np.identity(3)
print(identityMatrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# 6. Write a NumPy program to convert an array to a float type. 


In [ ]:
a = [1, 2, 3, 4]
print("Original array")
print(a)
x = np.asfarray(a)
print("Array converted to a float type:")
print(x)

Original array
[1, 2, 3, 4]
Array converted to a float type:
[1. 2. 3. 4.]


# 7. Write a NumPy program to generate five random numbers from the normal distribution. 

In [ ]:
x = np.random.normal(size=5)
print(x)

[ 1.41181035 -0.38350925 -0.72786784  0.96318464  0.19231379]


# 8. Following is the input NumPy array delete column two and insert following new column in its place. 
sampleArray=numpy.array([[34,43,73],[82,22,12],[53,94 , 66]])
newColumn = numpy.array([[10,10,10]]) 


In [ ]:
sampleArray=numpy.array([[34,43,73],[82,22,12],[53,94 , 66]])
print('Original Array\n',sampleArray)
newColumn = numpy.array([[10,10,10]]) 
sampleArray=numpy.delete(sampleArray,1,axis=1)
print('\nSecond row deleted\n',sampleArray)
sampleArray=numpy.insert(sampleArray,1,newColumn,axis=1)
print('\nNew Row Inserted\n',sampleArray)

Original Array
 [[34 43 73]
 [82 22 12]
 [53 94 66]]

Second row deleted
 [[34 73]
 [82 12]
 [53 66]]

New Row Inserted
 [[34 10 73]
 [82 10 12]
 [53 10 66]]


# 9. Write a NumPy program to compute the multiplication of two given matrices. 


In [ ]:
p = [[1, 0], [0, 1]]
q = [[1, 2], [3, 4]]
print("original matrix:")
print(p)
print(q)
result1 = np.dot(p, q)
print("Result of the said matrix multiplication:")
print(result1)

original matrix:
[[1, 0], [0, 1]]
[[1, 2], [3, 4]]
Result of the said matrix multiplication:
[[1 2]
 [3 4]]


# 10. Write a NumPy program to create a random vector of size 10 and sort it. 

In [ ]:
x = np.random.random(10)
print("Original array:")
print(x)
x.sort()
print("Sorted array:")
print(x)


Original array:
[0.19275    0.43397477 0.42429034 0.54901289 0.34904523 0.87687533
 0.13203991 0.41292123 0.12576218 0.7831055 ]
Sorted array:
[0.12576218 0.13203991 0.19275    0.34904523 0.41292123 0.42429034
 0.43397477 0.54901289 0.7831055  0.87687533]


# 11. Write a NumPy program to compute the covariance matrix of two arrays. 

In [ ]:
array1 = np.array([0, 1, 1])
array2 = np.array([2, 2, 1])

# Original array1
print(array1)

# Original array2
print(array2)

# Covariance matrix
print("\nCovariance matrix of the said arrays:\n",
	np.cov(array1, array2))


[0 1 1]
[2 2 1]

Covariance matrix of the said arrays:
 [[ 0.33333333 -0.16666667]
 [-0.16666667  0.33333333]]


# 12. Create a 4X2 integer array and Prints its 
: i)The shape of an array. 
ii) Array dimensions. 
 iii) The Length of each element of the array in bytes


In [ ]:
firstArray = numpy.empty([4,2], dtype = numpy.uint16) 
print("Printing Array")
print(firstArray)

print("Printing numpy array Attributes")
print("i) Array Shape is: ", firstArray.shape)
print("ii) Array dimensions are ", firstArray.ndim)
print("iii) Length of each element of array in bytes is ", firstArray.itemsize)

Printing Array
[[    0     0]
 [    0 16392]
 [    0     0]
 [    0 16392]]
Printing numpy array Attributes
i) Array Shape is:  (4, 2)
ii) Array dimensions are  2
iii) Length of each element of array in bytes is  2


# 13. Write a NumPy program to concatenate element-wise two arrays of string. 

In [ ]:
# creating array as first_name
first_name = np.array(['Akash', 'Ayush', 'Diksha',
                       'Radhika'], dtype = np.str)
print("Printing first name array:")
print(first_name)
 
# creating array as last name
last_name = np.array(['Kumar', 'Sharma', 'Tewari',
                      'Pegowal'], dtype = np.str)
print("Printing last name array:")
print(last_name)
 
# concat first_name and last_name
# into new array named as full_name
full_name = np.char.add(first_name, last_name)
print("\nPrinting concatenate array as full name:")
print(full_name)

Printing first name array:
['Akash' 'Ayush' 'Diksha' 'Radhika']
Printing last name array:
['Kumar' 'Sharma' 'Tewari' 'Pegowal']

Printing concatenate array as full name:
['AkashKumar' 'AyushSharma' 'DikshaTewari' 'RadhikaPegowal']


# 14. Write a NumPy program to capitalize the first letter, lowercase, uppercase, swapcase, title-case of all the elements of a given array. 


In [ ]:
x = np.array(['python', 'PHP', 'java', 'C++'], dtype=np.str)
print("Original Array:")
print(x)
capitalized_case = np.char.capitalize(x)
lowered_case = np.char.lower(x)
uppered_case = np.char.upper(x)
swapcased_case = np.char.swapcase(x)
titlecased_case = np.char.title(x)
print("\nCapitalized: ", capitalized_case)
print("Lowered: ", lowered_case)
print("Uppered: ", uppered_case)
print("Swapcased: ", swapcased_case)
print("Titlecased: ", titlecased_case)

Original Array:
['python' 'PHP' 'java' 'C++']

Capitalized:  ['Python' 'Php' 'Java' 'C++']
Lowered:  ['python' 'php' 'java' 'c++']
Uppered:  ['PYTHON' 'PHP' 'JAVA' 'C++']
Swapcased:  ['PYTHON' 'php' 'JAVA' 'c++']
Titlecased:  ['Python' 'Php' 'Java' 'C++']


# 15. Write a NumPy program to convert a given array into a list. 

In [ ]:
# create array
print("\nArray:")
arr = np.array([1, 2, 4, 5])  
print(arr)
print(type(arr))
  
# apply method
lis = arr.tolist()
  
# display list
print("\nList:")
print(lis)
print(type(lis))


Array:
[1 2 4 5]
<class 'numpy.ndarray'>

List:
[1, 2, 4, 5]
<class 'list'>


# 16. Write a NumPy program to compute the sum of all elements, sum of each column and sum of each row of a given array. 


In [ ]:
x = np.array([[0,1],[2,3]])
print("Original array:")
print(x)
print("Sum of all elements:")
print(np.sum(x))
print("Sum of each column:")
print(np.sum(x, axis=0))
print("Sum of each row:")
print(np.sum(x, axis=1))


Original array:
[[0 1]
 [2 3]]
Sum of all elements:
6
Sum of each column:
[2 4]
Sum of each row:
[1 5]


# 17. Write a NumPy program to create a random 10x4 array and extract the first five rows of the array and store them into a variable. 

In [ ]:
x = np.random.rand(10, 4)
print("Original array: ")
print(x)
y= x[:5, :]
print("First 5 rows of the above array:")
print(y)

Original array: 
[[0.41749048 0.65246009 0.99971012 0.58714641]
 [0.03205664 0.90895263 0.92973222 0.60325642]
 [0.47439345 0.32823024 0.34521269 0.94894652]
 [0.51510397 0.79366605 0.04650277 0.37696769]
 [0.5295408  0.25643023 0.49297154 0.77354508]
 [0.72304291 0.71436742 0.74460261 0.8249189 ]
 [0.42633796 0.79538658 0.17951754 0.29241964]
 [0.31617103 0.49921482 0.55508416 0.14520816]
 [0.54682906 0.91910058 0.67802017 0.06763609]
 [0.52264273 0.15127834 0.6952789  0.13810848]]
First 5 rows of the above array:
[[0.41749048 0.65246009 0.99971012 0.58714641]
 [0.03205664 0.90895263 0.92973222 0.60325642]
 [0.47439345 0.32823024 0.34521269 0.94894652]
 [0.51510397 0.79366605 0.04650277 0.37696769]
 [0.5295408  0.25643023 0.49297154 0.77354508]]


# 18. Write a NumPy program to get the unique elements of
a 1D and 2D array. 


In [ ]:
x = np.array([10, 10, 20, 20, 30, 30])
print("Original array:")
print(x)
print("Unique elements of the 1D array:")
print(np.unique(x))
x = np.array([[1, 1], [2, 3]])
print("\nOriginal array:")
print(x)
print("Unique elements of the 2D array:")
print(np.unique(x))

Original array:
[10 10 20 20 30 30]
Unique elements of the 1D array:
[10 20 30]

Original array:
[[1 1]
 [2 3]]
Unique elements of the 2D array:
[1 2 3]


# 19. Write a NumPy program to get the unique elements of an array. 
 arr= [ -10 12.12 -0.2] 

In [ ]:
arr= [ -10,12,12,-0.2]
rslt = np.unique(arr)

print(rslt)

[-10.   -0.2  12. ]


# 20. Write a NumPy program to save a given array to a text file and load it. You have to save and load files using numpy library .

In [ ]:
# Creating an array
List = [1, 2, 3, 4, 5]
Array = np.array(List)
 
# Displaying the array
print('Array:\n', Array)
file = open("file1.txt", "w+")
 
# Saving the array in a text file
content = str(Array)
file.write(content)
file.close()
 
# Displaying the contents of the text file
file = open("file1.txt", "r")
content = file.read()
 
print("\nContent in file1.txt:\n", content)
file.close()

Array:
 [1 2 3 4 5]

Content in file1.txt:
 [1 2 3 4 5]
